apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core-customer.fullname" . }}
  labels:
    {{- include "core-customer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "core-customer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "core-customer.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretRef }}
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
