apiVersion: v2
name: core-customer
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "17.11.6" # versión estable al momento de escribir esto
    repository: "https://charts.bitnami.com/bitnami"
